[package]
name = "influx_db_client"
version = "0.1.0"
authors = ["piaoliu <441594700@qq.com>"]

repository = "https://github.com/driftluo/InfluxDBClient-rs"
description = "InfluxDB Rust driver"
readme = "README.md"
keywords = ["influxdb"]
license = "MIT"

[dependencies]
hyper = "*"
serde_json = '*'